apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: {{ .Values.pvc.volumeName }}
   namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
  - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}   
